# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/gitpractice
    docker:
      - image: circleci/python:3.6.6

    # Specify the Xcode version to use
    macos:
      xcode: "8.3.3"

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Use pipenv to install dependencies
          command: |
            sudo pip install pipenv
            pipenv install requests
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      
      - run:
         name: Run Some Python
         command: pipenv run "python leechbot.py"

dependencies:
  override:
    - brew install swiftlint

