# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "8.3.3"

    steps:
      - checkout
      
      - run:
         name: Run Some Python
         command: python leechbot.py

      - run:
          name: Post to Github
          command: bash post_comment.sh

      - run:
          name: Update Brew 
          command: echo "brew update"

      - run:
          name: Install Swiftlint
          command: echo "brew install swiftlint"

      - run:
          name: Run Swiftlint
          command: echo "swiftlint"

dependencies:
  override:
    - brew install swiftlint

