# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "8.3.3"

    steps:
      - checkout
      - run:
         name: Run Some Python
         command: python test.py

      - run:
          name: Post to Github
          command: |
            if [[ true ]]; then
              curl -X POST \
              -H 'Authorization: bearer 93f68858a6956bf34a5ae0e28fbf30d538cc2bc5' \
              -H 'Content-Type: application/json' \
              -d '{ \
                \"query\": \"mutation { addComment(input:{clientMutationId: \"1234\", subjectId: \"MDExOlB1bGxSZXF1ZXN0MjE2MTUwMzk4\", body: \"Looks good to me again from CircleCI\"}) { clientMutationId commentEdge {node {body      }}}}\" \
              }' \
              " https://api.github.com/graphql
            fi

      - run:
          name: Update Brew 
          command: echo "brew update"

      - run:
          name: Install Swiftlint
          command: echo "brew install swiftlint"

      - run:
          name: Run Swiftlint
          command: echo "swiftlint"

dependencies:
  override:
    - brew install swiftlint

